### ISSUE TITLE
Model preview not textured if textures do not have mipmaps

### ISSUE THREAD

**Issue by DeathChaos25** [TGEnigma/GFD-Studio#17]
Textures work fine in the games, but model preview is not correctly textured if mipmaps dont exist in the texture.

**Comment by DniweTamp** [comment]
You forgot to paste a screenshot of how it looks like without mipmaps
![image](https://user-images.githubusercontent.com/39583006/90018409-89f5cc80-dcb5-11ea-8c1d-0b6e39828eed.png)

Here's how it's supposed to look like (screenshot of textures with mipmaps):
![image](https://user-images.githubusercontent.com/39583006/90018537-bf021f00-dcb5-11ea-94a4-443358a3edee.png)
