### ISSUE TITLE
PNG Import defaults to DXT1

### ISSUE THREAD

**Issue by Alan3DDD** [TGEnigma/GFD-Studio#20]
When the original texture is DXT1 GFDStudio will default to it when replacing it with a PNG, it'd be nice to have an option or straight up default to DXT5 always because as far as I'm aware theres no instances where DXT1 is a requirement.

**Comment by Alan3DDD** [comment]
nvm DC betrayed me

**Comment by TGEnigma** [comment]
It uses DXT5 if the bitmap has transparency, if not it uses DXT1. I don't see how there's anything to be gained from using DXT5 with opaque textures?

**Comment by Alan3DDD** [comment]
Was under the impression the bigger number the better compresion but that seems to only apply to beyond DXT5, my bad.
