### ISSUE TITLE
No GNF textures (in the GMD/GFS model packs) support, also no uncompressed DDS support

### ISSUE THREAD

**Issue by DniweTamp** [TGEnigma/GFD-Studio#24]
Usually all Persona/Catherine models have DDS textures, but PS4 releases of P3D/P5D use GNF for textures
I already know that GFD Studio supports GNF textures, but it can only load them as separate files, not when reading a model, so I guess it just always expects to see a DDS texture when loading a file?

The other thing is that it does not load GMD/GFS models that have uncompressed DDS textures (such as em0745 from P5R, Yu Enemy model). That model uses one uncompressed DDS texture for a sword trail effect, but that is enough to kill the whole program.

**Comment by Master-s** [comment]
Can you edit the PS5 .gnf file that has a dynamic image

Download gnf
https://mega.nz/file/kGhmRRLS#xWNR8gsK6I47ckDa6ue9Rh_qXJqhQWTZ3HwEPm5RVzI
