### ISSUE TITLE
FBX Export busted in latest release build, spits out broken ASCII FBX files

### ISSUE THREAD

**Issue by Iamgoofball** [TGEnigma/GFD-Studio#9]
The files don't seem to be valid according to Autodesk's FBX converter. They all fail with the following error:
`Call to FbxImporter::Initialize() failed. Error: Corrupted or invalid file.`

I was using two of Rise's models from Persona 4 Dancing to export.

**Comment by Ariq139** [comment]
You aren't supposed to export models to FBX using the GFD Studio. Use the 3DS Max script instead.

**Comment by TGEnigma** [comment]
While Assimp (the library used to import/export model files) supports importing from FBX files, it doesn't support exporting to the format unfortunately.

**Comment by Iamgoofball** [comment]
Ah, alright. The export options tricked me lol
